### ISSUE TITLE
Bottom toolbar affect the normal operation of the web page

### ISSUE THREAD

**Issue by YeeJone** [MobileChromeApps/mobile-chrome-apps#637]
![image](https://user-images.githubusercontent.com/20400822/110293925-23a61200-802a-11eb-83ca-3c4040b8cf44.png)

The style of the bottom div  
```css
.ModalContent {
    position: fixed;
    bottom: 0;
    ...
}
```
I think that toolbar should not affect the normal operation of the page...   

Recurrence path:
Click this link from your memo    https://www.zhihu.com/question/52082799/answer/1735551823

iphone 11 iOS 14.4
chrome：87.0.4280.77
